ci: tidy go mod and show diff/error on dirty
Signed-off-by: Sergei Lukianov <me@slukjanov.name>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -68,16 +68,23 @@ jobs:
           version: v0.27.0
           cluster_name: kind
 
-      - name: Install CRDs
+      - name: Install CRDs into Kind
         run: |
           just --timestamp test-api
+
+      - name: Go mod tidy
+        run: |
+          go mod tidy
+          go mod vendor
 
       # Don't remove it! We shouldn't allow CI to pass if there are any changes not committed after running gen/lint/test
       - name: Fail on dirty
         run: |
-          git diff
-          git status --short
-          git diff --quiet
+          if ! git status --short || ! git diff --quiet; then
+            git --no-pager diff -- . :^vendor
+            echo "::error::Working directory is dirty. Please run 'just gen lint && go mod tidy && go mod vendor' and commit the changes."
+            exit 1
+          fi
 
       - name: Setup tmate session for debug
         if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
